name: Run Test
on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    # - name: Test
    #   run: make test

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        install-only: true

    - name: Test
      run: make build

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: fruits_api
        path: src/dist/*
        if-no-files-found: warn
        retention-days: 1
        compression-level: 6
