name: Build app

on:
  push:
    branches: ['main']

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build binary
      run: make build

    - uses: actions/upload-artifact@v4
      with:
        name: fruits_api
        path: ./fruits_api
        if-no-files-found: warn
        retention-days: 30
        compression-level: 6

    - uses: rymndhng/release-on-push-action@v0.28.0
      id: release
      with:
        bump_version_scheme: minor
        tag_prefix: v

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        tags: |
          ghcr.io/${{ github.repository_owner }}/fruits_api:${{ steps.vars.outputs.sha_short }}
          ghcr.io/${{ github.repository_owner }}/fruits_api:${{ steps.release.outputs.version }}
          ghcr.io/${{ github.repository_owner }}/fruits_api:latest